version: "3"

services:
  python3:
    build:
      context: .
      dockerfile: application/Dockerfile
    container_name: "cf_python"
    working_dir: "/home/"
    tty: true
    volumes:
      - ./application/app:/home
